import sys
import logging
from pathlib import Path
from typing import List, Any, Optional

# Ensure project root is in sys.path regardless of working directory
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from app.agent.agent import Agent

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("agent_service")

# ---------------------------------------------------------------------------
# FASTAPI APPLICATION SETUP
# ---------------------------------------------------------------------------
app = FastAPI(
    title="SIH 26117 Agent Service",
    description="Dedicated microservice exposing the intelligent reasoning Agent orchestration layer.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

# Enable CORS for communication with frontend / main backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Singleton Agent holder with lazy-loading support
_agent_instance: Optional[Agent] = None


def get_agent() -> Agent:
    """
    Returns the initialized Agent instance.
    Uses lazy initialization so the service starts cleanly and retries
    if dependencies (like Qdrant or embedding models) become available.
    """
    global _agent_instance
    if _agent_instance is None:
        try:
            logger.info("Initializing Agent instance...")
            _agent_instance = Agent()
            logger.info("Agent instance initialized successfully.")
        except Exception as e:
            logger.exception("Failed to initialize Agent instance: %s", e)
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Agent initialization failed: {str(e)}"
            )
    return _agent_instance


@app.on_event("startup")
def startup_event():
    """
    Attempt pre-initialization on startup. If an external lock exists
    (e.g., another process holding local Qdrant storage), log a warning
    and allow lazy-loading on request.
    """
    global _agent_instance
    try:
        _agent_instance = Agent()
        logger.info("Agent pre-initialized on startup.")
    except Exception as e:
        logger.warning(
            "Agent could not be pre-initialized at startup (will retry on request): %s", e
        )


# ---------------------------------------------------------------------------
# REQUEST & RESPONSE MODELS
# ---------------------------------------------------------------------------
class ChatRequest(BaseModel):
    """
    Request model for the Agent chat endpoint.
    Primary field is `question`. Optional fields provide future readiness
    for Vision, OCR, and multimodal document workflows without breaking changes.
    """
    question: str = Field(
        ...,
        description="The user's query or instruction for the Agent."
    )
    image_base64: Optional[str] = Field(
        default=None,
        description="Reserved for future vision analysis."
    )
    file_path: Optional[str] = Field(
        default=None,
        description="Reserved for future document inspection/OCR."
    )

    class Config:
        json_schema_extra = {
            "example": {
                "question": "What is the maintenance procedure?"
            }
        }


class ChatResponse(BaseModel):
    """
    Response model returning the Agent's answer and execution metadata.
    """
    answer: str = Field(..., description="The final synthesized answer generated by the agent.")
    steps: List[str] = Field(default_factory=list, description="Execution steps performed during reasoning.")
    sources: List[Any] = Field(default_factory=list, description="Retrieved evidence sources if RAG was used.")
    intent: str = Field(default="unknown", description="The classified user intent.")
    status: str = Field(default="completed", description="Execution status (e.g., completed, failed).")


class HealthResponse(BaseModel):
    status: str
    service: str


# ---------------------------------------------------------------------------
# API ENDPOINTS
# ---------------------------------------------------------------------------
@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Health check endpoint",
    tags=["System"]
)
def health():
    """
    Returns service health status.
    """
    return {
        "status": "ok",
        "service": "agent"
    }


@app.post(
    "/v1/chat",
    response_model=ChatResponse,
    summary="Agent Chat and Reasoning Endpoint",
    tags=["Agent"]
)
def chat(req: ChatRequest):
    """
    Process a question through the Agent reasoning loop:
    1. Validates the question.
    2. Retrieves or initializes the existing Agent class.
    3. Streams execution via agent.run_stream(question).
    4. Collects tokens, logs, and done results.
    5. Returns a structured JSON response.
    """
    # 1. Validate the question
    cleaned_question = req.question.strip() if req.question else ""
    if not cleaned_question:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The 'question' field cannot be empty or contain only whitespace."
        )

    # 2. Get existing Agent instance
    agent = get_agent()

    # 3. Execution tracking state
    collected_tokens: List[str] = []
    collected_steps: List[str] = []
    sources: List[Any] = []
    intent: str = "unknown"
    final_answer: str = ""
    status_str: str = "completed"

    # 4. Stream and collect events
    try:
        logger.info("Executing Agent for query: %s", cleaned_question[:100])

        for event in agent.run_stream(cleaned_question):
            event_type = event.get("type")

            if event_type == "step":
                msg = event.get("message")
                if msg:
                    collected_steps.append(msg)

            elif event_type == "classification":
                intent = event.get("intent", intent)

            elif event_type == "token":
                token_text = event.get("content", "")
                collected_tokens.append(token_text)

            elif event_type == "retrieval":
                retrieved_sources = event.get("sources", [])
                if retrieved_sources:
                    sources = retrieved_sources

            elif event_type == "done":
                result = event.get("result", {})
                final_answer = result.get("answer", "")
                if result.get("sources"):
                    sources = result.get("sources", [])
                if result.get("steps"):
                    collected_steps = result.get("steps", collected_steps)
                if result.get("intent"):
                    intent = result.get("intent", intent)
                if result.get("status"):
                    status_str = result.get("status", status_str)

        # Fallback to token concatenation if done event did not contain answer
        if not final_answer and collected_tokens:
            final_answer = "".join(collected_tokens)

        return {
            "answer": final_answer,
            "steps": collected_steps,
            "sources": sources,
            "intent": intent,
            "status": status_str,
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Agent execution encountered an unhandled error")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Agent execution failed: {str(e)}"
        )


# ---------------------------------------------------------------------------
# DIRECT LAUNCH
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app.agent.main:app", host="0.0.0.0", port=8001, reload=True)
